name: Add Secrets
run-name: Add Secrets

on:
  workflow_dispatch:
    inputs:
      secret_key:
        description: Secret Key
        required: true
        type: string
      secret_value:
        description: Secret Value
        required: true
        type: string

jobs:
  add-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mask Secret
        run: |
          SECRET_VALUE=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
          echo ::add-mask::$SECRET_VALUE
          echo SECRET_VALUE=$SECRET_VALUE >> $GITHUB_ENV

      - name: Show Secret
        run: |
          echo "Secret Name: ${{ inputs.secret_key }}"
          echo "Secret Value: $SECRET_VALUE"
